Datetime:2025-05-23 21:42:01,222 - Level:INFO - Module:database_utils - Function:clear_all_tables - Message:Successfully dropped 1 tables
Datetime:2025-05-23 21:42:01,239 - Level:INFO - Module:database_utils - Function:clear_all_views - Message:No views to clear
Datetime:2025-05-23 21:42:01,970 - Level:ERROR - Module:exchanges_update - Function:exchanges_update - Message:EODHD exchange headers do not match expected format
Datetime:2025-05-23 21:42:01,970 - Level:ERROR - Module:exchanges_update - Function:exchanges_update - Message:Failed to update exchanges
Traceback (most recent call last):
  File "/home/jamesallen/projects/Project_Seldon/lib/data_centre/database/scripts/exchanges_update.py", line 158, in exchanges_update
    raise ValueError("Exchange column headers mismatch")
ValueError: Exchange column headers mismatch
Datetime:2025-05-23 22:05:53,732 - Level:INFO - Module:database_utils - Function:clear_all_tables - Message:Successfully dropped 1 tables
Datetime:2025-05-23 22:05:53,754 - Level:INFO - Module:database_utils - Function:clear_all_views - Message:No views to clear
Datetime:2025-05-23 22:05:54,514 - Level:ERROR - Module:database_utils - Function:db_connection - Message:Database error: 1054 (42S22): Unknown column 'EoDHD_Code' in 'INSERT INTO'
Datetime:2025-05-23 22:05:54,514 - Level:ERROR - Module:exchanges_update - Function:exchanges_update - Message:Failed to update exchanges
Traceback (most recent call last):
  File "/home/jamesallen/projects/Project_Seldon/.venv/lib/python3.13/site-packages/mysql/connector/connection_cext.py", line 772, in cmd_query
    self._cmysql.query(
    ~~~~~~~~~~~~~~~~~~^
        query,
        ^^^^^^
    ...<3 lines>...
        query_attrs=self.query_attrs,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
_mysql_connector.MySQLInterfaceError: Unknown column 'EoDHD_Code' in 'INSERT INTO'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jamesallen/projects/Project_Seldon/lib/data_centre/database/scripts/exchanges_update.py", line 168, in exchanges_update
    database_utils.execute_query(db_config, query)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/jamesallen/projects/Project_Seldon/lib/data_centre/database/utils/database_utils.py", line 40, in execute_query
    cursor.execute(query)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/home/jamesallen/projects/Project_Seldon/.venv/lib/python3.13/site-packages/mysql/connector/cursor_cext.py", line 356, in execute
    self._connection.cmd_query(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._stmt_partition["mappable_stmt"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        raw_as_string=self._raw_as_string,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/jamesallen/projects/Project_Seldon/.venv/lib/python3.13/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 97, in wrapper
    return method(cnx, *args, **kwargs)
  File "/home/jamesallen/projects/Project_Seldon/.venv/lib/python3.13/site-packages/mysql/connector/connection_cext.py", line 781, in cmd_query
    raise get_mysql_exception(
        err.errno, msg=err.msg, sqlstate=err.sqlstate
    ) from err
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'EoDHD_Code' in 'INSERT INTO'
Datetime:2025-05-23 22:05:54,520 - Level:ERROR - Module:initialise_database - Function:main - Message:Database initialization failed: 1054 (42S22): Unknown column 'EoDHD_Code' in 'INSERT INTO'
Datetime:2025-05-23 22:07:18,916 - Level:INFO - Module:database_utils - Function:clear_all_tables - Message:Successfully dropped 1 tables
Datetime:2025-05-23 22:07:18,937 - Level:INFO - Module:database_utils - Function:clear_all_views - Message:No views to clear
Datetime:2025-05-23 22:07:19,734 - Level:INFO - Module:exchanges_update - Function:exchanges_update - Message:Added 4 new exchanges to database
Datetime:2025-05-23 22:07:27,700 - Level:INFO - Module:tickers_update - Function:tickers_update - Message:Added 55233 new tickers to database
Datetime:2025-05-23 22:08:16,654 - Level:INFO - Module:database_utils - Function:clear_all_tables - Message:Successfully dropped 6 tables
Datetime:2025-05-23 22:08:16,672 - Level:INFO - Module:database_utils - Function:clear_all_views - Message:No views to clear
Datetime:2025-05-23 22:08:17,389 - Level:INFO - Module:exchanges_update - Function:exchanges_update - Message:Added 4 new exchanges to database
Datetime:2025-05-23 22:08:17,389 - Level:INFO - Module:initialise_database - Function:main - Message:Database initialization completed successfully
Datetime:2025-05-23 22:09:14,377 - Level:INFO - Module:database_utils - Function:clear_all_tables - Message:Successfully dropped 1 tables
Datetime:2025-05-23 22:09:14,401 - Level:INFO - Module:database_utils - Function:clear_all_views - Message:No views to clear
Datetime:2025-05-23 22:09:15,143 - Level:INFO - Module:exchanges_update - Function:exchanges_update - Message:Added 77 new exchanges to database
Datetime:2025-05-23 22:09:15,144 - Level:INFO - Module:initialise_database - Function:main - Message:Database initialization completed successfully
Datetime:2025-05-23 22:18:47,272 - Level:INFO - Module:database_utils - Function:clear_all_tables - Message:Successfully dropped 1 tables
Datetime:2025-05-23 22:18:47,295 - Level:INFO - Module:database_utils - Function:clear_all_views - Message:No views to clear
Datetime:2025-05-23 22:18:48,040 - Level:INFO - Module:exchanges_update - Function:exchanges_update - Message:Added 77 new exchanges to database
Datetime:2025-05-23 22:20:12,265 - Level:INFO - Module:tickers_update - Function:tickers_update - Message:Added 208722 new tickers to database
Datetime:2025-05-23 22:20:12,265 - Level:INFO - Module:initialise_database - Function:main - Message:Database initialization completed successfully
